### ISSUE TITLE
emoji.decode() is fundamentally broken, not needed, and should be removed.

### ISSUE THREAD

**Issue by geowurster** [carpedm20/emoji#10]
@carpedm20 having `emoji.EMOJI_UNICODE` gives us an easy way to look up unicode codes by emoji and `emoji.UNICODE_EMOJI` gives us an easy way to look up emoji names by unicode codes, but multiple aliases point to the same unicode code so we can't do reverse alias lookups.  See the sample code below.  About 400 aliases are dropped.

`emoji.decode()` really isn't that useful and I vote we just remove it.  Any objections?

```python
>>> import emoji
>>> len(emoji.EMOJI_UNICODE)
1282
>>> len(emoji.UNICODE_EMOJI)
1282
>>> len(emoji.EMOJI_ALIAS_UNICODE)
1694
>>> len(emoji.UNICODE_EMOJI_ALIAS)
1279
```

**Comment by carpedm20** [comment]
No objection. Just remove it.

**Comment by errror** [comment]
Sorry, but I do not understand, why decode() is not useful. I use it in my code to generate readable codes from UTF8 emojis. How should I do this now? Directly accessing your internal data structures seems not the best idea to me.

**Comment by geowurster** [comment]
@errror the problem lies in the aliases.  Multiple aliases use the same UTF code so the name returned by `decode()` in those cases is somewhat arbitrary.  We could limit `decode()` to just be the official unicode codes but could lead to some confusion.  I suppose just letting the returned name be arbitrary for the aliases isn't a huge deal, and we could add a `use_aliases` option to turn them on and off.

@carpedm20 thoughts?

**Comment by errror** [comment]
@geowurster I can live much better with a function, picking *one* of the possible representations instead of none at all. Reading UTF8 emojis in the debug output is much harder.

**Comment by geowurster** [comment]
@errror so would the most useful implementation be the inverse of `emojize()`, which takes a string that may contain UTF emoji codes and replaces them with the corresponding `:emoji:` name?

**Comment by errror** [comment]
@geowurster Yes, that's what I need in my code.

**Comment by geowurster** [comment]
Closing in favor of #14 for re-implementation.
