### ISSUE TITLE
Release v0.3.4

### ISSUE THREAD

**Issue by geowurster** [carpedm20/emoji#11]
- [x] Merge #7.
- [x] Close out https://github.com/carpedm20/emoji/milestones/v0.3.4.
- [x] Update changelog with mention of aliases and restoration of default functionality.
- [x] Make sure aliases are properly documented after the recent changes. 
- [x] Create a `v0.3-maint` branch as a safety measure and keep it in git.
- [ ] Tag a release in GitHub.
- [x] Upload to PyPi.

**Comment by geowurster** [comment]
@carpedm20 unless you have anything else to add I vote we release after #13.

**Comment by geowurster** [comment]
Just installed the update and everything works again.  Success!

**Comment by carpedm20** [comment]
Great! :smile:
