### ISSUE TITLE
Some emoji doesn't work

### ISSUE THREAD

**Issue by gshefer** [carpedm20/emoji#113]
```python
>>> import emoji
>>> for i in str(emoji.EMOJI_ALIAS_UNICODE).split(':'):
...        if 'smile' in i:
...            print(i)
...        
cat_face_with_wry_smile
smile_cat
smiley_cat
smiley
sweat_smile
smile
>>> emoji.emojize(':smiley:')
':smiley:'
>>> emoji.emojize(':thumbs_up:')
'👍'

```

Where is my smiley??

**Comment by YuKitAs** [comment]
It also happened to me, some smileys just don't work.

**Comment by troldmand** [comment]
Also happened to me: 

`
# Templates
def random_emoji(i):
        switcher={
            1: emoji.emojize(':thumbs_up:'),
            2: emoji.emojize(':fire:'),
            3: emoji.emojize(':collision:'),
            4: emoji.emojize(':pray:'),
            5: emoji.emojize(':fist:'),
            6: emoji.emojize(':heartpulse:'),
            7: emoji.emojize(':scream:'),
            8: emoji.emojize(':dancer:')

        }
        return switcher.get(i,"Invalid")

# test of emojis
print('TEST OF EMOJIS')

for x in range(1,8):
    print(random_emoji(x))
`

prints:
```
TEST OF EMOJIS
👍
🔥
💥
:pray:
:fist:
:heartpulse:
:scream:
```

**Comment by truthdoug** [comment]
You'll need to add `use_aliases=True` to the `emojize()` call. Per the readme:

> By default only the official list is enabled but doing `emoji.emojize(use_aliases=True)` enables both the full list and aliases.


```
# Templates
def random_emoji(i):
        switcher={
            1: emoji.emojize(':thumbs_up:', use_aliases=True),
            2: emoji.emojize(':fire:', use_aliases=True),
            3: emoji.emojize(':collision:', use_aliases=True),
            4: emoji.emojize(':pray:', use_aliases=True),
            5: emoji.emojize(':fist:', use_aliases=True),
            6: emoji.emojize(':heartpulse:', use_aliases=True),
            7: emoji.emojize(':scream:', use_aliases=True),
            8: emoji.emojize(':dancer:', use_aliases=True)

        }
        return switcher.get(i,"Invalid")

# test of emojis
print('TEST OF EMOJIS')

for x in range(1,8):
    print(random_emoji(x))
```

produces:

```
TEST OF EMOJIS
👍
🔥
💥
🙏
✊
💗
😱
```

**Comment by rishabh-gupta-fk** [comment]
print("So pretty 🧡🧡🧡".encode('unicode_escape'))
print(emoji.demojize("So pretty 🧡🧡🧡"))
