### ISSUE TITLE
Find all the distinct emojis present in the list

### ISSUE THREAD

**Issue by aashish-chaubey** [carpedm20/emoji#120]
Given a sentence, I would like to find out all the distinct number of emojis in a list:

For example:

> 'Hey 😷😷😷'

The function should return `['😷']`

> 'Hey 😷😷🇬🇧'

The function should return `['😷', '🇬🇧']`

Any help will be appreciated!

**Comment by truthdoug** [comment]
You'll probably have better luck asking this sort of question on StackOverflow.

**Comment by XWilliamY** [comment]
You can try the following:

```
import re

text = "hello there 👧"
unique_emojis = set(re.findall(emoji.get_emoji_regexp(), text))
```

Or if you'd also like to count how many of each emoji there are:

```
from collections import Counter
text = "hello there 👧"
unique_emojis_count = Counter(re.findall(emoji.get_emoji_regexp(), text))
```
