### ISSUE TITLE
Some emoji Detection is missing?

### ISSUE THREAD

**Issue by DataPsycho** [carpedm20/emoji#136]
My colleague shared that image in our slack channel and joking that emoji library is racist I hope not 🧑🏽‍🦱. But I guess its just missing some emoji signature probably; may be we can add them. Here in the left side there is actual text and in the right side he have implemented a lambda function to search the emojies but using emoji library he was not able to find the darker emojies.
🤞🏾 
![image](https://user-images.githubusercontent.com/10431123/95335524-cefe3f80-08af-11eb-80c9-3798a891f7fa.png)

Thanks

**Comment by tahirjalilov** [comment]
I think it's because the last pack of emojis added to the project was from emoji v.12 (https://emojipedia.org/emoji-12.0/)
I'm gonna add emojis from version 12.1/13/13.1 and 14. Give me a time ))))
