### ISSUE TITLE
Colorless Emojis

### ISSUE THREAD

**Issue by HilitOreny** [carpedm20/emoji#138]
Dear maintainers,

The official documentation presents emojis in different colors:
[https://pypi.org/project/emoji/](url)
[https://emojis.readthedocs.io/en/latest/](url)

Yet, when I run the emoji module, the emojis are colorless.

For example, when I run the following code:
![code](https://user-images.githubusercontent.com/69712717/96672776-b42ad100-136d-11eb-8376-4193389e57d4.jpg)

I get a colorless thumbs-up emoji
![output](https://user-images.githubusercontent.com/69712717/96672773-b2f9a400-136d-11eb-9e58-75c9f3b90edc.jpg)

instead of the yellow thumbs-up emoji shown here:
[https://pypi.org/project/emoji/](url)

My operating system is Windows 10 Home 64-bit and I use the latest version of python (3.9.0).

Can you please fix this bug?
I appreciate your help!

**Comment by tahirjalilov** [comment]
it's because you are using a terminal or python console and emojis can not be colored there
