### ISSUE TITLE
:pinched_fingers: (🤌) isn't in `emoji.UNICODE_EMOJI`

### ISSUE THREAD

**Issue by CircuitSacul** [carpedm20/emoji#142]
This emoji is new in 2020, so I'd assume that's why it isn't here yet. Would you be willing to add it though?

https://emojipedia.org/pinched-fingers/

**Comment by tahirjalilov** [comment]
it's because the last pack of emojis added to the project was from emoji v.12 (https://emojipedia.org/emoji-12.0/)
I'm gonna add emojis from version 12.1/13/13.1 and 14. Give a time ))))

**Comment by tellarin** [comment]
I'm having a similar problem, but with OK Hand (\U0001f44c). Since the release of v1.0 builds and packages are breaking.

**Comment by TahirJalilov** [comment]
@tellarin  nope nothing was removed from the old list of emojis. OK_hand is still in the list line number 241
https://github.com/carpedm20/emoji/blob/master/emoji/unicode_codes/en.py#L241
