### ISSUE TITLE
Some emojis no longer in after the release of the PyPI package for v1? 

### ISSUE THREAD

**Issue by tellarin** [carpedm20/emoji#151]
We've started facing an issue with some emojis are no longer included in UNICODE_EMOJI. For example, the OK Hand emoji (\U0001f44c). 

All worked fine in v0.6.0, but since the release of v1.0 builds and downstream packages are breaking.

Or was this a breaking change in the structure of UNICODE_EMOJI? I so, I'd suggest having a field just for the code points.

**Comment by TahirJalilov** [comment]
Since release v.1.0.0 Multilanguage support added to the project. Maybe the reason for your problem is it.
The "OK hand" emoji is still there https://github.com/carpedm20/emoji/blob/master/emoji/unicode_codes/en.py#L241

**Comment by TahirJalilov** [comment]
@tellarin may I close this issue?

**Comment by tellarin** [comment]
I get what you meant, and I now am referencing UNICODE_EMOJI["en"] to keep the previous behaviour. So I guess it can be closed.
But I'd suggest the emoji package expose some field that has only the Unicode code points for emojis (without the natural-language-like aliases, and without any language specific mapping) for ease of checks against it. That would be a valuable feature of the lib.

**Comment by TahirJalilov** [comment]
I think it's a good idea )) added to my todo list )) Thank you!
