### ISSUE TITLE
module 'emoji' has no attribute 'get_emoji_regexp'

### ISSUE THREAD

**Issue by MysteryxD** [carpedm20/emoji#154]
The below error is popped up

![IMG_20210126_205813](https://user-images.githubusercontent.com/75388792/105865911-659a6c00-6019-11eb-831c-f4b38e84d0cd.jpg)

I've made sure that there is no file or directory named 'emoji'.
I didn't change the code even a bit, and it was working totally fine few days ago. 
But today I realized this error popping up. 
What's new? 👀

**Comment by TahirJalilov** [comment]
this is my output.
![image](https://user-images.githubusercontent.com/43037294/105874250-cfb11200-6015-11eb-8730-d965e6852e5b.png)

**Comment by TahirJalilov** [comment]
@MysteryxD did you check it again? May I close this issue?

**Comment by MysteryxD** [comment]
It's weird problem n i checked it again n again but still it's the same. But i can't understand what it is. But of course it will be problem from my side n i will think about it
