### ISSUE TITLE
Cannot check whether the char is emoji or not with emoji.UNICODE_EMOJI

### ISSUE THREAD

**Issue by nuetoban** [carpedm20/emoji#155]
It looks like versions 1.1.0 and 1.0.0 have invalid UNICODE_EMOJI variable.

```python3
>>> from emoji import UNICODE_EMOJI
>>> '🔑' in UNICODE_EMOJI
False
>>> '🤔' in UNICODE_EMOJI
False
>>> '💦' in UNICODE_EMOJI
False
>>> '🔕' in UNICODE_EMOJI
False
>>> '' in UNICODE_EMOJI
False
```

The version 0.6.0 works perfectly.
```python3
>>> from emoji import UNICODE_EMOJI
>>> '🔕' in UNICODE_EMOJI
True
>>> '💦' in UNICODE_EMOJI
True
>>> '' in UNICODE_EMOJI
False
```

**Comment by TahirJalilov** [comment]
From the v.1.0.0 added support for multilingual naming of emojis. Now UNICODE_EMOJI has language keys
UNICODE_EMOJI = {
    'en': UNICODE_EMOJI_ENGLISH,
    'es': UNICODE_EMOJI_SPANISH,
    'pt': UNICODE_EMOJI_PORTUGUESE,
    'it': UNICODE_EMOJI_ITALIAN,
}

**Comment by exelestor** [comment]
Got it. Sorry!

**Comment by nuetoban** [comment]
I got it. Sorry!
