### ISSUE TITLE
Release v0.3.5

### ISSUE THREAD

**Issue by geowurster** [carpedm20/emoji#16]
@carpedm20 I think this packaging issue might be affecting a lot of people so unless you have anything else to add I vote we do this as a patch and then do #14 (and anything else that pops up before it is implemented) in the next release.

- [x] Update changelog
- [x] Pull onto `v0.3-maint` branch
- [x] Tag a release in GitHub
- [x] Push to PyPi

**Comment by carpedm20** [comment]
I don't fully understand the meaning of `Pull onto v0.3-maint branch`. Can you explain about this in more detail?

**Comment by geowurster** [comment]
Sure.  If we keep a copy of `v0.3` on the `v0.3-maint` branch that matches what's in PyPi, then as we continue to develop for the next version we can quickly release a patch for `v0.3` if needed.

In git terms:

```console
$ git checkout master
$ git pull
$ git checkout -b v0.3-maint
$ git rebase master
$ git push
```

There are a [few different ways](http://stackoverflow.com/questions/5613902/how-to-pull-from-a-local-branch-into-another-one) to pull master onto the maintenance branch but apparently `rebase` is the cleanest.

You probably just got some GitHub notifications from me accidentally pushing to a branch in this repo.  Ignore those - I undid that push.  I was testing the commands to make sure I was right.

**Comment by carpedm20** [comment]
Thank you for your detailed description :+1:
