### ISSUE TITLE
Missing ❤️ emoji

### ISSUE THREAD

**Issue by CircuitSacul** [carpedm20/emoji#164]
<img width="248" alt="Screen Shot 2021-04-12 at 7 55 21 PM" src="https://user-images.githubusercontent.com/55721663/114476841-0506de00-9bc9-11eb-9c0d-a8443daeb490.png">

I also tried the other 3 language codes, still got nothing.

**Comment by CircuitSacul** [comment]
<img width="487" alt="Screen Shot 2021-04-13 at 12 37 33 PM" src="https://user-images.githubusercontent.com/55721663/114588834-1ac1e500-9c55-11eb-983e-fdef640b19c9.png">

**Comment by cvzi** [comment]
The problem is that there can be invisible characters after the emoji. You can check it like so:
```python
len("❤")   # returns length 1
len("❤️")   # returns length 2
```
If the length is greater than 1 then there are invisible characters after the emoji. They might change the appearance of the emoji. In this case they switch the emoji between looking like an emoji (red heart) and looking like text (black heart).

You can create them like this to test it:
```python
emoji.emojize(":red_heart:")  # "❤"  with length = 1
emoji.emojize(":red_heart:", variant="text_type")  # "❤︎"  with length = 2
emoji.emojize(":red_heart:", variant="emoji_type")  # "❤️"  with length = 2
```

**Comment by CircuitSacul** [comment]
Since this is in the context of a discord bot, I can't control the length of the input, so how would I solve this problem?

**Comment by cvzi** [comment]
What exactly are you trying to achieve?
Generally I would suggest to use the demojize function and work with the result
```python
emoji.demojize("❤️")   # returns  ":red_heart:"
```

**Comment by CircuitSacul** [comment]
I need to validate that the emoji is actually an emoji, so that I can react to messages with it later

**Comment by cvzi** [comment]
You can check if the return value of demojize is different from the original string:
```python
s = "❤️"
if emoji.demojize(s) != s:
    # s contains an emoji
else:
    # s does not contain an emoji
```

**Comment by CircuitSacul** [comment]
How would I extract the emoji, and only the emoji? That method would allow "bla :emoji: bla" to pass

**Comment by cvzi** [comment]
You could extract the text between the two colons. For example with a regular expression:

```python
s = "bla ❤️ bla ⭐ bla"
decoded = emoji.demojize(s)   # = 'bla :red_heart: bla :star: bla'
if emoji.demojize(s) != s:
    single_emoji = re.search(":[^:]+:", decoded)[0]   # = ':red_heart:'

```

**Comment by CircuitSacul** [comment]
I had to replace `search` with `findall`, but that works. Thanks
