### ISSUE TITLE
emoji unicode set

### ISSUE THREAD

**Issue by mbande** [carpedm20/emoji#18]
does this package contain all of [emoji-data v1.0](http://unicode.org/Public/emoji/1.0/emoji-data.txt)

**Comment by tgwizard** [comment]
Hi @mbande. I just did a check, and all emojis in http://unicode.org/Public/emoji/1.0/emoji-data.txt are contained in this package. One extra character is there as well, as described in #20.

**Comment by Vantuz** [comment]
It would also be useful if you added emojis from [3.0](http://unicode.org/Public/emoji/3.0/emoji-data.txt) standard

**Comment by truthdoug** [comment]
There have been at least two major updates of unicode emojis since this issue was last commented on.

This issue can be closed.
