### ISSUE TITLE
only red heart emoji i can see in the console not others.

### ISSUE THREAD

**Issue by Rishi-Ratan-Pandey** [carpedm20/emoji#182]
import emoji

 print(emoji.emojize("Python Is Fun:red_heart:"))#it displays ❤ in the console

let's say i want to print thumbs up emoji in the console
import emoji
print(emoji.emojize("Python Is Fun:thumbs_up:"))#it not display thumbs up emoji in the console
why thumbs up emoji is not  prints in the console???

**Comment by TahirJalilov** [comment]
Maybe it depends on your console or installed fonts

**Comment by TahirJalilov** [comment]
may I close this issue?
