### ISSUE TITLE
速度很慢且匹配的时候会将一个完整的emoji做拆分，并且有的emoji匹配不到。

### ISSUE THREAD

**Issue by Alone749-i** [carpedm20/emoji#194]
我在处理大量包含emoji数据的时候发现关于emoji匹配的位置，代码运行效率很低，并且会将一个完整的组合emoji拆分进行匹配。有些emoji匹配不上，希望给出一些解决方案。

**Comment by TahirJalilov** [comment]
Hello @Alone749-i could you please describe your problem in English?
