### ISSUE TITLE
Windows Version

### ISSUE THREAD

**Issue by jak645** [carpedm20/emoji#2]
Mmmm i try to install this on python for windows but noting work do you have tutorial or other code

**Comment by carpedm20** [comment]
#3 (version 0.2.0) doesn't fix the problem on windows yet.

**Comment by matteocontrini** [comment]
Isn't this solved yet? :)

**Comment by geowurster** [comment]
@matteocontrini can you send the error you get on Windows?  I don't think either one of us regularly use Windows.

**Comment by geowurster** [comment]
@matteocontrini could you also try this:


```
pip uninstall emoji && pip install git+https://github.com/carpedm20/emoji.git@update-packaging --upgrade --no-cache
```

Sometimes pip gets confused so I tacked an explicit uninstall command on the front and forced it to download with --no-cache. Verify that it installed `v0.3.5` with:

```
python -c "import emoji; print(emoji.__version__)"
0.3.5
```

**Comment by nh-99** [comment]
Windows error:
```
      File "C:\Python34\lib\encodings\cp1252.py", line 23, in decode

        return codecs.charmap_decode(input,self.errors,decoding_table)[0]

    UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 315:
character maps to <undefined>
```

**Comment by geowurster** [comment]
@nh-99 is that just with `pip install emoji` or from the branch outlined above?

**Comment by nh-99** [comment]
That is with a pip install emoji.

**Comment by nh-99** [comment]
Okay tested with the command above, worked perfectly
