### ISSUE TITLE
The dataset in unicodes_code.py contains helm_symbol not in the Unicode standard

### ISSUE THREAD

**Issue by tgwizard** [carpedm20/emoji#20]
In an attempt to answer #18, I compared the contents in the `EMOJI_UNICODE` dict with that in http://www.unicode.org/emoji/charts/full-emoji-list.html (by using `utils/get-codes-from-unicode-consortium.py`). It seems that all characters are present, but there is one extra character: `:helm_symbol:`. More info about that character here: http://www.fileformat.info/info/unicode/char/2388/index.htm

Why is U+2638 included as an emoji? Perhaps that character should be in a separate dict of characters that are often treated as emojis?

**Comment by geowurster** [comment]
@tgwizard Good catch.  If its not an emoji then it should probably be removed.  I'm not sure how it was originally included - maybe it was listed on that page when I scraped it several months ago?  In `unicode_codes.py` I'm seeing `:wheel_of_dharma:` as `2368` and `:helm_symbol:` as `2388`:

```console
':wheel_of_dharma:': u'\U00002638',
':helm_symbol:': u'\U00002388',
```

Looks like `:wheel_of_dharma:` is in the page referenced by #18 as `2638`, so it should probably stay and `':helm_symbol:': u'\U00002388',` should go?

**Comment by tgwizard** [comment]
Ah, yes, that seems to be it.

**Comment by tgwizard** [comment]
I can submit a PR removing the helm symbol, and updating the README to say which unicode symbols are included. @geowurster what do you think?

**Comment by geowurster** [comment]
@tgwizard I'm :+1: @carpedm20 does this sound right?

There's already a note in the readme about which codes are included, but if you didn't see it or if it wasn't clear enough then it probably does need to be updated.  If you're thinking about adding the full table to the readme, I don't think we need that.  Adding more docs will close out #18.

**Comment by tgwizard** [comment]
Ah, yes, I didn't see that note, but I think it is clear enough as is.
