### ISSUE TITLE
Proposal: Strict demojize

### ISSUE THREAD

**Issue by reustle** [carpedm20/emoji#201]
It would be great to demojize a string without replacing emojis with shortcodes.

Judging by a few posts I've found ([like this](https://stackoverflow.com/questions/33404752/removing-emojis-from-a-string-in-python)), it seems like others would find this useful, too.

For example:

```python
foo = "Hello 🌎"

print(emoji.demojize(foo))
# "Hello :world:"

print(emoji.demojize(foo, delete=True))
# "Hello "
```

After looking through the codebase, I found `emoji.replace_emoji(my_string, replace="")` which seems to do what we're looking for, but it isn't clear if it's recommended or documented.

Thanks so much for maintaining this great library.

**Comment by cvzi** [comment]
Yes `emoji.replace_emoji(my_string, replace="")` is the correct way to do it.

**Comment by cvzi** [comment]
I guess we lack a documentation at the moment, we only have the python docstrings in the code. 
We should at least have an overview of all the public methods. Could probably be auto-generated from those docstrings.
