### ISSUE TITLE
Multi-person skin tones

### ISSUE THREAD

**Issue by cvzi** [carpedm20/emoji#204]
[Multi-Person Skin Tones on unicode.org](http://www.unicode.org/reports/tr51/#multiperson_skintones)

Edit: here's a tool to create these: https://codepen.io/cvzi/full/RwQNJBK

These are currently not RGI by unicode (Recommended for General Interchange), which means they should not be generated with `emojize()`. 
However they work in some phones and browsers. For example a family of 4 persons with 4 different skin tones: 👨🏽‍👩🏿‍👧🏻‍👦🏾 
This emoji consists of:
* 👨🏽 `:man_medium_skin_tone:`
* \u200d [ZWJ](http://www.unicode.org/reports/tr51/#Emoji_ZWJ_Sequences) 
* 👩🏿 `:woman_dark_skin_tone:`
* \u200d ZWJ
* 👧🏻 `:girl_light_skin_tone:`
* \u200d ZWJ
* 👦🏾 `:boy_medium-dark_skin_tone:`

`demojize()` currently converts that emoji to:
`'👨:medium_skin_tone:\u200d👩:dark_skin_tone:\u200d:girl_light_skin_tone:\u200d:boy_medium-dark_skin_tone:'`

Possible solutions:

Convert the man and woman as well to (minimal solution):
*  `:man::medium_skin_tone:\u200d:woman::dark_skin_tone:\u200d:girl_light_skin_tone:\u200d:boy_medium-dark_skin_tone:`

or combine the skin tones into man and woman as well:
*  `:man_medium_skin_tone:\u200d:woman_dark_skin_tone:\u200d:girl_light_skin_tone:\u200d:boy_medium-dark_skin_tone:`

remove the skin tones
*  `:family_man_woman_girl_boy:'`

Or with the skin tones:
*  `:family_man_woman_girl_boy_medium_dark_light_skin_medium-dark_tone:'`

Edit:

Probably the easiest one is this:
`:man_medium_skin_tone:\u200d:woman_dark_skin_tone:\u200d:girl_light_skin_tone:\u200d:boy_medium-dark_skin_tone:`

Have to decide if we want to remove the `\u200d` or not. 
If we keep the `\u200d`, `emojize()` can revert the string correctly i.e. `emojize(demojize(str)) == str`. 
I don't know what's the effect of having them though, `:\u200d:` might be displayed strangely.

**Comment by cvzi** [comment]
Could you open this again, it's actually still a bug. 

Not sure why I referenced it in v2.0.0, that was wrong

**Comment by lsmith77** [comment]
Let me pre-face that what I am doing is replacing emoji with alternatives ones.

f.e. replacing a `women` with `person` or `man` with `women`. I am also replacing skin tones, offering either a version without a skin tone or offering alternative skin tones.

Generally I think it makes sense to be able to do something like `demojize(emojize(demojize(some_emoji)))` so I would either keep `\u200d` or return a list in `demojize()` which could then also be handled by `emojize()`.

For my use case a list could be convenient since I would want to iterate over all of the "sub-emoji" to create permutations of modified emojis.

**Comment by cvzi** [comment]
Thanks for you input!

I agree a list of the "sub-emoji" might be nice. Possibly a list could be available in the callback of `replace_emoji()` or returned by `emoji_list()`

**Comment by lsmith77** [comment]
in my case I am processing emoji one at a time using https://github.com/explosion/spacymoji

Note they  currently creating [separate tokens](https://github.com/explosion/spacymoji) for `\u200d` delimited emoji.

**Comment by cvzi** [comment]
I will add a new function to the module (probably call it `emoji.analyze(string)`) that can "tokenize" the string into a list of emoji and non-emoji chars. 
If the found emoji is a ZWJ-emoji, then offer some way to detect/split the "sub-emoji".

**Comment by cvzi** [comment]
FYI these changes will remove support for Python 2.7 and probably 3.5.

Ref #243
