### ISSUE TITLE
Replacement for `emoji.get_emoji_regexp()`

### ISSUE THREAD

**Issue by fotoente** [carpedm20/emoji#207]
In the new Version 2.0.0 the function `emoji.get_emoji_regexp()` will be replaced.
I am using it not to delete, but to find all UTF emojis in a given string and count them. The deprecation warning only hints how to remove emojis in future.

Will there be a replacement for that function to find all emojis, just like `emoji.get_emoji_regexp()`?

**Comment by cvzi** [comment]
There are the function `emoji.emoji_list()`, `emoji.distinct_emoji_list()` and `emoji.emoji_count()`
see issue #206 for an example of the list, for the others you have to look at the docstrings in [core.py](https://github.com/carpedm20/emoji/blob/master/emoji/core.py)

(excuse the brevity I am on my phone) 
-- 
Enviado desde mi dispositivo Android con K-9 Mail. Por favor, disculpa mi brevedad.

**Comment by cvzi** [comment]
We now have a documentation with examples:
https://carpedm20.github.io/emoji/docs/#extracting-emoji
