### ISSUE TITLE
Docs link gives a 404

### ISSUE THREAD

**Issue by amadejpapez** [carpedm20/emoji#210]
Documentation link in the README gives a GitHub Pages 404 error.

https://carpedm20.github.io/emoji works but https://carpedm20.github.io/emoji/docs/ doesn't seem to be available.

**Comment by cvzi** [comment]
The documentation needs to build and deployed to the github pages by the Github action

@TahirJalilov can you create a new release to trigger the github action (or run the workflow manually without a new release at https://github.com/carpedm20/emoji/actions/workflows/updateGithubPages.yml)

**Comment by TahirJalilov** [comment]
@cvzi all jobs have failed

**Comment by TahirJalilov** [comment]
fixed.
