### ISSUE TITLE
module 'emoji' has no attribute 'UNICODE_EMOJI'

### ISSUE THREAD

**Issue by KaiyeYang-git** [carpedm20/emoji#218]
I have no idea why the latest version didn't include this function and which version I can use this function?

**Comment by cvzi** [comment]
Version `emoji==1.7.0` is the last version that has `UNICODE_EMOJI`.

You can also try to use `EMOJI_DATA`as a replacement for `UNICODE_EMOJI`. If you explain how you use `UNICODE_EMOJI` or show your code, I can give more specific help.

**Comment by KaiyeYang-git** [comment]
> Version `emoji==1.7.0` is the last version that has `UNICODE_EMOJI`.
> 
> You can also try to use `EMOJI_DATA`as a replacement for `UNICODE_EMOJI`. If you explain how you use `UNICODE_EMOJI` or show your code, I can give more specific help.

Cheers, it works when I degrade to v1.7
