### ISSUE TITLE
module 'emoji' has no attribute 'get_emoji_regexp'

### ISSUE THREAD

**Issue by yusuffgur** [carpedm20/emoji#219]
I do not why but I can not import this module?

**Comment by cvzi** [comment]
That function was removed in version 2.0.0 of the module. See here: https://carpedm20.github.io/emoji/docs/#regular-expression

If you explain how you used `get_emoji_regexp()` or show your code snippet, I can give more specific help.

**Comment by yusuffgur** [comment]
Thank you very much, ı was trying to import them for my course lab and get error.
