### ISSUE TITLE
AttributeError: module 'emoji' has no attribute 'UNICODE_EMOJI'

### ISSUE THREAD

**Issue by mvitha** [carpedm20/emoji#221]
I am getting this error - can anyone help w a fix?

**Comment by cvzi** [comment]
The property `UNICODE_EMOJI` was removed in version 2.0.0 of this module.

You can try to use [`EMOJI_DATA`](https://carpedm20.github.io/emoji/docs/api.html#emoji.EMOJI_DATA) as a replacement for `UNICODE_EMOJI`. If you explain how you use `UNICODE_EMOJI` or show your code snippet, I can give you more specific help.

You can also downgrade the module version to `emoji~=1.6.3` and stay with the old version that has the `UNICODE_EMOJI` property, but that means you will miss out on new emoji in the future

**Comment by mvitha** [comment]
Wow thank you so much for the prompt reply! 

we are using this as part of an NLP script to identify emojis and remove string as part of text cleaning/preprocessing

code below: 

  ```
def pull_emojis(self):
    # Function for getting emojis from one string
    get_emojis_1str = lambda word_list: collections.Counter([char for word in word_list for char in word if char in emoji.UNICODE_EMOJI['en']])

    # Function for removing emojis from one word
    remove_emojis_1word = lambda word: "".join([char for char in word if char not in emoji.UNICODE_EMOJI['en']])

    # Function for removing emojis from one string
    remove_emojis_1str = lambda word_list: list(map(remove_emojis_1word, word_list))

    # Function for removing empty strings from a word list
    remove_empty_str = lambda word_list: [word for word in word_list if word != '']

    # Get emojis from each string and remove them from each original string
    self.emojis = pd.Series(list(map(get_emojis_1str, self.strings)))
    self.strings = pd.Series(list(map(remove_emojis_1str, self.strings)))
    self.strings = pd.Series(list(map(remove_empty_str, self.strings)))
```

**Comment by cvzi** [comment]
You can use `emoji.emoji_list(str)` to get a list of all emoji in a string:
```python
emoji.emoji_list("Hi, I am fine. 😁💀")
[{'match_start': 15, 'match_end': 16, 'emoji': '😁'}, {'match_start': 16, 'match_end': 17, 'emoji': '💀'}]
```
And you can use `emoji.replace_emoji(str, '')` to remove emoji from string (i.e. replace with empty string)
```python
emoji.replace_emoji("Hi, I am fine. 😁💀", replace='')
"Hi, I am fine.  "
```

So something like this:
```python
  # Function for getting emojis from one string
  get_emojis_1str = lambda word_list: collections.Counter([match["emoji"] for word in word_list for match in emoji.emoji_list(word)])

  # Function for removing emojis from one word
  remove_emojis_1word = lambda word: emoji.replace_emoji(word, replace='')

```

I can see in your code, that you have iterated over characters in a string (`char for char in word`) to find/remove the emoji. This works only for emoji that are one character long, but there are also emoji that span over multiple characters. Your code would have ignored these longer emoji. If you use the functions `emoji_list`, then it will also find emoji that span over multiple characters. So keep in mind that an emoji can be longer than one character.

**Comment by mvitha** [comment]
This is brilliant. Thank you so much for this. Will implement and let you know how it all goes

**Comment by lingvisa** [comment]
Hi, I have a similar question. If I want to check whether a string is an emoji or not, I tried:

```
def is_emoji(text):
    return text in emoji.UNICODE_EMOJI_ENGLISH
```

But it says that emoji doesn't have the attribute "UNICODE_EMOJI_ENGLISH", but I saw it is defined in the code. Why is it that?

**Comment by cvzi** [comment]
@lingvisa It was also removed in version 2.0.0 of the module. You can check like this now:
```python 
text in emoji.EMOJI_DATA
```

There is also a `is_emoji()` function already defined in the module, so you can simply do `emoji.is_emoji(your_text)`. It is defined here:
https://github.com/carpedm20/emoji/blob/c398e0c5ff6ceff08c7860078b242765f093f285/emoji/core.py#L279-L281

**Comment by lingvisa** [comment]
That's awesome. Another question regarding the 'language' argument. Is emoji detection universal to all languages, or has something to do with a particular language? I tested the default English emoji in Chinese and it seems it can detect the emoji in Chinese text too. Can you explain a bit on the language argument?

**Comment by cvzi** [comment]
@lingvisa For the detection the language argument is not used and the language of the text does not matter.

(In older versions of the module there were some differences depending on language but it is no longer the case)

Also the language argument only applies to the two functions `emojize()` and `demojize()`:
The language argument is only for converting emoji to `:emoji_name:` and the reverse `:emoji_name:` to emoji. The language changes the name of the emoji:
```python
# English
emoji.emojize('Python is :thumbs_up:', language='en') 
'Python is 👍'

# Spanish
emoji.emojize('Python is :pulgar_hacia_arriba:', language='es') 
'Python is 👍'

# and reverse:

# English
emoji.demojize('Python is 👍', language='en')
'Python is :thumbs_up:'

# Spanish
emoji.demojize('Python is 👍', language='es')
'Python is :pulgar_hacia_arriba:'

```

For this conversion to names, the Chinese names are not yet included but we plan to add Chinese soon.

**Comment by lingvisa** [comment]
I see and thanks.

**Comment by bjmgeek** [comment]
> You can try to use [`EMOJI_DATA`](https://carpedm20.github.io/emoji/docs/api.html#emoji.EMOJI_DATA) as a replacement for `UNICODE_EMOJI`. If you explain how you use `UNICODE_EMOJI` or show your code snippet, I can give you more specific help.

Thanks. This worked.  I was trying to get a list of all emoji characters for the purpose of picking a random emoji.  I was using `random.choice(list(emoji.UNICODE_EMOJI.keys())`
I can modify my code to use `random.choice(list(emoji.EMOJI_DATA.keys()))`

**Comment by masudtalukdar** [comment]
> The property `UNICODE_EMOJI` was removed in version 2.0.0 of this module.
> 
> You can try to use [`EMOJI_DATA`](https://carpedm20.github.io/emoji/docs/api.html#emoji.EMOJI_DATA) as a replacement for `UNICODE_EMOJI`. If you explain how you use `UNICODE_EMOJI` or show your code snippet, I can give you more specific help.
> 
> You can also downgrade the module version to `emoji~=1.6.3` and stay with the old version that has the `UNICODE_EMOJI` property, but that means you

> The property `UNICODE_EMOJI` was removed in version 2.0.0 of this module.
> 
> You can try to use [`EMOJI_DATA`](https://carpedm20.github.io/emoji/docs/api.html#emoji.EMOJI_DATA) as a replacement for `UNICODE_EMOJI`. If you explain how you use `UNICODE_EMOJI` or show your code snippet, I can give you more specific help.
> 
> You can also downgrade the module version to `emoji~=1.6.3` and stay with the old version that has the `UNICODE_EMOJI` property, but that means you will miss out on new emoji in the future

Thanks , Problem solved

**Comment by ibriiee** [comment]
hey i am facing a problem to get to know the emotions of a text with this code :- 

import emoji
text = "I am feeling today!"
# extract all emojis from the text
emojis = ''.join(c for c in text if c in emoji.UNICODE_EMOJI)
print(emojis)

i changed it with emoji_data then it just displays the emojy. what i want exactly is :--

import text2emotion as te
text= "I hate Kaggle Community Pakistan"
te.get_emotion(text)

and the output show be link this : -
{'Happy': 1.0, 'Angry': 0.0, 'Surprise': 0.0, 'Sad': 0.0, 'Fear': 0.0}

How can i do it can anyone help me out ?

**Comment by cvzi** [comment]
I don't understand what the problem is. What do you expect that `print(emojis)` shows?

If it worked before and you replace `UNICODE_EMOJI` with `EMOJI_DATA` it should work again, that is the new way of doing it, since version 2.0.0 of this library.

**Comment by ibriiee** [comment]
> I don't understand what the problem is. What do you expect that `print(emojis)` shows?
> 
> If it worked before and you replace `UNICODE_EMOJI` with `EMOJI_DATA` it should work again, that is the new way of doing it, since version 2.0.0 of this library.
> 
> Please put three ``` (backquote) before and after your code to display it properly

I want to extract emotion for the text, in other workds i want to know the sentiment of the text it should be working like this:-


input
````` > import text2emotion as te
      >text= "I hate Kaggle Community Pakistan"
      >te.get_emotion(text)
````

output
`````
{'Happy': 1.0, 'Angry': 0.0, 'Surprise': 0.0, 'Sad': 0.0, 'Fear': 0.0}
`````

**Comment by cvzi** [comment]
@ibriiee I think it would be better to ask in the repository of text2emotion https://github.com/aman2656/text2emotion-library/issues

**Comment by ibriiee** [comment]
> @ibriiee I think it would be better to ask in the repository of text2emotion https://github.com/aman2656/text2emotion-library/issues

thanks for the suggestion

**Comment by bibinkunjumon2020** [comment]
> You can use `emoji.emoji_list(str)` to get a list of all emoji in a string:
> 
> ```python
> emoji.emoji_list("Hi, I am fine. 😁💀")
> [{'match_start': 15, 'match_end': 16, 'emoji': '😁'}, {'match_start': 16, 'match_end': 17, 'emoji': '💀'}]
> ```
> 
> And you can use `emoji.replace_emoji(str, '')` to remove emoji from string (i.e. replace with empty string)
> 
> ```python
> emoji.replace_emoji("Hi, I am fine. 😁💀", replace='')
> "Hi, I am fine.  "
> ```
> 
> So something like this:
> 
> ```python
>   # Function for getting emojis from one string
>   get_emojis_1str = lambda word_list: collections.Counter([match["emoji"] for word in word_list for match in emoji.emoji_list(word)])
> 
>   # Function for removing emojis from one word
>   remove_emojis_1word = lambda word: emoji.replace_emoji(word, replace='')
> ```
> 
> I can see in your code, that you have iterated over characters in a string (`char for char in word`) to find/remove the emoji. This works only for emoji that are one character long, but there are also emoji that span over multiple characters. Your code would have ignored these longer emoji. If you use the functions `emoji_list`, then it will also find emoji that span over multiple characters. So keep in mind that an emoji can be longer than one character.

This saved my issue:
i wanted to avoid emojis in my input text:
message_text = update.message.text
        try:
            list_of_emojis = emoji.emoji_list(message_text) # listing emojis in user input to avoid processing
            
            if isinstance(message_text,str) and len(list_of_emojis) == 0:

**Comment by ghaskari** [comment]
Install this version of emoji 
 
emoji==1.7.0

**Comment by saqib772** [comment]
Hey All, I making The Chat Analyzer and need to show the bar with respect to user, How much emojis they have used. I tried the following code and it generates the result not as Expected. Skips Many Emojis.

CODE:

```
def emoji_select(selected_user,df):
    if selected_user!='Overall':
        df=df[df['user']==selected_user]
    
    emojis=[]
    for m in df['user_message']:
       emojis.extend([c for c in m if c in emoji.EMOJI_DATA])

    emoji_df=pd.DataFrame(Counter(emojis).most_common(len(Counter(emojis))))

    return emoji_df
    
    ```
    
    
![image](https://github.com/carpedm20/emoji/assets/121972215/6beda0c5-8009-45b3-8ee4-3fe9b5617772)

This is Pandas Dataframe
![image](https://github.com/carpedm20/emoji/assets/121972215/5a1fbc6a-9237-467b-a7ce-3094480e443e)

It don't show emoji correctly in bar chart but it does in dataFrame. Any Solution.

**Comment by shruti-jain10** [comment]
emoji_df = helper.emoji_helper(selected_user,df)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\whatsapp chat analyzer\helper.py", line 88, in emoji_helper
    emojis.extend([c for c in message if c in emoji.EMOJI_DATA['emoji']])
                                              ~~~~~~~~~~~~~~~~^^^^^^^^^
KeyError: 'emoji'


how to resolve this error?

**Comment by cvzi** [comment]
Replace the emojis.extend(... line with:

emojis.extend([e['emoji'] for e in emoji.emoji_list(message)])
-- 
Enviado desde mi dispositivo Android con K-9 Mail. Por favor, disculpa mi brevedad.

**Comment by VelmuruganRavichandran** [comment]
Downgrade the emoji version 

pip install emoji==1.7.0 --force-reinstall
