### ISSUE TITLE
2.0.0: No Emoji Regex anymore?

### ISSUE THREAD

**Issue by E-Aho** [carpedm20/emoji#222]
Hey! Was wondering why the decision was made to remove the functionality of the get_regexp() method completely, instead of marking it deprecated or some other change?

It was breaking change, and a slightly odd choice to remove outright, but I'm sure there was a reason.

**Comment by cvzi** [comment]
The regular expression was slow on Python 3.7 and became even slower with the following Python versions. In rare cases it failed to match emoji correctly. Internally the regular expression was therefore not used anymore.

It was then completely removed in this major version change from 1.x.y -> 2.0.0 (it was previously deprecated in 1.7.0). The module offers its own methods to find, replace and remove emoji, so a slow and faulty regular expression shouldn't be necessary.

For now you can still use the old version of the module `emoji~=1.6.3` (or 1.7.0 but it has deprecation warnings). New emoji are scheduled to be released in September if I remember correctly, so it will probably take until next year for them to arrive on mobile phones. At least until then, you can use the old version of the module without drawbacks.

**Comment by E-Aho** [comment]
I can understand the thinking with that. 
I did use the get_regexp() function in a project I was working on, particularly for a process that required a regex pattern to work, but I can understand why this package made the choice to remove the function.
