### ISSUE TITLE
AttributeError: module 'emoji' has no attribute 'get_emoji_regexp'

### ISSUE THREAD

**Issue by Fred-Wu** [carpedm20/emoji#223]
I encountered this error after the recent update. Is there anyway to fix this?

**Comment by Fred-Wu** [comment]
I just reverted to v1.7, and saw the deprecation message. With the new version, how can I achieve the following

```
emoji.get_emoji_regexp().search(ch)
```

**Comment by cvzi** [comment]
If you want to find emoji in a string, you can use [emoji.emoji_list()](https://carpedm20.github.io/emoji/docs/api.html#emoji.emoji_list) as a replacement.

See https://github.com/carpedm20/emoji/issues/222#issuecomment-1200303280 and https://carpedm20.github.io/emoji/docs/#migrating-to-version-2-0-0 for more information
