### ISSUE TITLE
Unable to print a red heart!

### ISSUE THREAD

**Issue by odebroqueville** [carpedm20/emoji#224]
I'm using the latest emoji version from conda-forge, i.e. v1.7.0.

I tested the following python code:

```
import sys
import emoji
print(sys.version)
print(emoji.emojize('Python is :thumbs_up:'))
print(emoji.emojize("I :red_heart: Python", variant="emoji_type"))
print(emoji.emojize("Python is fun :yellow_heart:", variant="emoji_type"))
```

RESULTS:

<img width="772" alt="Screenshot 2022-08-04 at 22 45 44" src="https://user-images.githubusercontent.com/4818315/182949363-4e8102d0-3568-4638-b6a1-d66f22c022b5.png">

**Comment by cvzi** [comment]
Could you try what happens if you copy and paste the output to somewhere else. For example in your browser, e.g. post it here as a comment. 
Or the other way, copy `❤️` from here and paste it into your terminal.

If it changes color, then your terminal just doesn't support these emoji yet.

**Comment by odebroqueville** [comment]
Here is the output copied from my terminal in Visual Studio Code. Funny thing is all the colours work except red!

3.9.12 (main, Apr  5 2022, 01:53:17) 
[Clang 12.0.0 ]
Python is 👍
I ❤️ Python
Python is fun 💛

<img width="651" alt="Screenshot 2022-08-05 at 16 57 31" src="https://user-images.githubusercontent.com/4818315/183104071-65ffad5c-9b08-452e-b91d-a2e61d00fc82.png">

And this is the result in iTerm:

<img width="651" alt="Screenshot 2022-08-05 at 16 59 51" src="https://user-images.githubusercontent.com/4818315/183104582-e2c3cfa2-c46f-4684-991e-3eaa0a4efc0f.png">

So, looks like you're right and the terminal in Visual Studio Code isn't displaying the red heart. I wonder how I can correct this.

**Comment by cvzi** [comment]
I don't know how this can be fixed either.

The red heart is "special". It is derived from the black heart (black heart has already existed in unicode before emoji).

The red heart has a text_type and an emoji_type. The other hearts are "normal" emoji, with only emoji_type.
(There are other emoji that have text_type and emoji_type though)

That means, the red heart is represented in unicode by U+2764 (=black heart `❤`) followed by U+fe0f (=emoji_type). If an app doesn't support this indication for emoji_type with U+fe0f, it will just show the black heart and ignore the U+fe0f.

**Comment by odebroqueville** [comment]
In any case, thank you for helping me identify where the problem lies. Have a great weekend.
