### ISSUE TITLE
PyPI wheel

### ISSUE THREAD

**Issue by groodt** [carpedm20/emoji#226]
The benefits of wheels are well documented. See: https://pythonwheels.com/
This package is pure Python and publishing it as both source and as a wheel is simple.

Would you accept a PR to publish a wheel?

**Comment by groodt** [comment]
Any thoughts @TahirJalilov @cvzi ?

**Comment by cvzi** [comment]
I am not involved in the packaging/publishing. I would agree though.

Looks like TahirJalilov hasn't been active on Github since the last release. I'll write him an email if he doesn't reply in the next few days.

**Comment by TahirJalilov** [comment]
@groodt Hello, it's good idea, I will accept your PR
