### ISSUE TITLE
Python 3.10 / Pycharm 2022.1.3 Cannot find reference 'is_emoji' in '__init__.pyi'

### ISSUE THREAD

**Issue by UAShota** [carpedm20/emoji#228]
In pycharm this sample has error - Cannot find reference 'is_emoji' in '__init__.pyi'

import emoji

print(emoji.is_emoji("1"))

But code working, just ome bug :)

**Comment by cvzi** [comment]
Maybe Pycharm uses an old version of typeshed. The data was just updated 21 days ago on typeshed, see https://github.com/python/typeshed/pull/8426

There is a description here on how to override it if it's outdated: https://www.jetbrains.com/help/pycharm/type-hinting-in-product.html#57fdfb39
