### ISSUE TITLE
AttributeError someone can help me

### ISSUE THREAD

**Issue by jfreitas123** [carpedm20/emoji#232]
I've imported the library "emoji" to a code and appear this error

Traceback (most recent call last):
  File "C:\Users\jpf_l\PycharmProjects\CursoemVideo\aula 08\emoji.py", line 1, in <module>
    import emoji
  File "C:\Users\jpf_l\PycharmProjects\CursoemVideo\aula 08\emoji.py", line 2, in <module>
    print(emoji.emojize('Python is :thumbsup:', language='alias'))
AttributeError: partially initialized module 'emoji' has no attribute 'emojize' (most likely due to a circular import). Did you mean: 'emoji'?

my email jp752749@gmail.com

![WhatsApp Image 2022-09-25 at 4 49 56 PM](https://user-images.githubusercontent.com/114361775/192162473-ffdabd85-fe70-43fe-9c27-bc3317c7cc50.jpeg)
![WhatsApp Image 2022-09-25 at 4 49 47 PM](https://user-images.githubusercontent.com/114361775/192162475-eda45dfd-4244-4515-b727-5b4c8cc6998f.jpeg)

**Comment by cvzi** [comment]
I think you have to change the name of your file. If the filename is `emoji.py` then `import emoji` may try to import the file `emoji.py` and not the library. Try something like `my_emoji.py`

**Comment by jfreitas123** [comment]
> I think you have to change the name of your file. If the filename is `emoji.py` then `import emoji` may try to import the file `emoji.py` and not the library. Try something like `my_emoji.py`

Thank you men, it worked!
