### ISSUE TITLE
How to know if my terminal can display emojis?

### ISSUE THREAD

**Issue by buhtzz** [carpedm20/emoji#233]
I couldn't find that topic in the documentation.

Maybe it is not the job of your package itself. But maybe you have an idea or a hint how to solve that.

How can I test if the terminal my scripts runs in is able to display your emojis?

For example I often use SSH terminals including tmux; sometimes windows SSH client, sometimes a Linux terminal emu (which should be able to show the emojis).

**Comment by cvzi** [comment]
On Unix you can count the column length of printed characters with the [`wc`](https://manpages.org/wc) program (if the installed version supports the `-L` parameter):
```python
emj = emoji.emojize(":red_heart:").encode()
p = subprocess.run(["wc", "-L"], input=emj, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
print(int(p.stdout.decode()))
```
This should print 0 for emoji that are not supported and > 0 for supported emoji. That way you could check all the emoji you want to use.

Whether you run a local script or a ssh session, should not matter. Except if the remote uses a different encoding than the local terminal,  in that case there could be problems.

I don't know how it can be checked on Windows.

**Comment by buhtzz** [comment]
Nice approach. But didn't work. The result is always `1`. Checked that on Windows as SSH client using tmux on a Debian 11 and on an Xfce terminal (via RDP) on the same machine.

**Comment by cvzi** [comment]
I thought this used to work, but thinking about it now, this `wc` program might just use a hard-coded Unicode table to calculate the column width, which would be useless if the font can't display the emoji-character. 

I am not aware of another solution. I know in browsers they check the support for emoji by drawing the emoji and then inspecting the pixels to check if it was actually drawn. I don't think something like that can be done in the terminal though.
