### ISSUE TITLE
Missing emojis.

### ISSUE THREAD

**Issue by fabiocaccamo** [carpedm20/emoji#234]
Hello, 
I'm printing on a webpage some texts taken from GitHub repositories that contains some emojis.

The emojis used are all supported by GitHub and present in this collection https://github.com/ikatyang/emoji-cheat-sheet but calling `emoji.emojize(text, language="alias")` on the texts I noticed that some emojis are missing, eg:

- :it: `:it:`
- :zombie_man: `:zombie_man:`

I know that these aliases are not official, but it would be nice to support them since they are supported by GitHub.

**Comment by fabiocaccamo** [comment]
@cvzi thank you for the detailed explanation.

I partially solved my problem replacing `:zombie_man:` with `:zombie:`, but for the flag actually there is not solution, because GitHub doesn't show `:Italy:` and the `emoji` library doesn't show `:it:`.

**Comment by TahirJalilov** [comment]
> Do you know why they were not added? Should we add them?
Hmm, it's very interesting. Maybe they were added to the https://www.webfx.com/tools/emoji-cheat-sheet/ after emoji package was created. Anyway, I think we should add all missing aliases.

**Comment by fabiocaccamo** [comment]
@TahirJalilov how are updated emojis/aliases actually, manually or is there some script for doing it?

**Comment by cvzi** [comment]
There is a script in `utils/get_codes_from_unicode_emoji_data_files.py` and manually is also possible, the script should keep manually added stuff intact.
Initially there wasn't a script, someone must have added the aliases by hand or with a private script. I am pretty sure the two-letter-codes have always been on the emoji-cheat-sheet, so someone must have decided not to add them. 
Some time ago I changed the script to fetch the aliases from Github API at https://api.github.com/emojis
I tried to not make to many changes, so I added this check to not add these two-letter-code aliases:
https://github.com/carpedm20/emoji/blob/b27cf787deaec7cf8349aa3c3b6f5f9e9aca7378/utils/get_codes_from_unicode_emoji_data_files.py#L277-L279
Hopefully when I remove this check, it will add the two-letter-codes automatically.

For the `:zombie_man:` I'll have to make some more adjustments as described above. There may be some more aliases with the same problem.

I'll do it in the next few days.
Maybe I combine it with adding the new emoji from Unicode 15.0 [#235 ](https://github.com/carpedm20/emoji/issues/235) and add some missing translations (the problem from #231 also applies to the existing languages not just Turkish)

**Comment by fabiocaccamo** [comment]
@cvzi maybe a cool improvement could be to automate emoji data updates running a GitHub action once a week/month. I did it once [here](https://github.com/fabiocaccamo/python-codicefiscale/blob/master/.github/workflows/update-data.yml), a script that writes some json files is executed, then the json files are pushed to the repo.

**Comment by cvzi** [comment]
> @cvzi maybe a cool improvement could be to automate emoji data updates running a GitHub action once a week/month. I did it once [here](https://github.com/fabiocaccamo/python-codicefiscale/blob/master/.github/workflows/update-data.yml), a script that writes some json files is executed, then the json files are pushed to the repo.

I think at the moment it is not worth it.

New emojis are appearing only once a year at the moment (in the future probably less).
Translations appear maybe two or three times a year, but there is usually some manual work involved and they need to be checked and old translations might have to be removed by hand.

BTW we also have something similar in the repo https://github.com/carpedm20/emoji/blob/master/.github/workflows/updateGithubPages.yml
That action updates the Github pages at https://carpedm20.github.io/emoji/
