### ISSUE TITLE
emoji.get_emoji_regexp

### ISSUE THREAD

**Issue by Shin-yue** [carpedm20/emoji#240]
how about that? emoji.get_emoji_regex I didn't find this

**Comment by cvzi** [comment]
This function has been removed in version 2.0.0 of the module.
You can either use one of the alternative functions described here: https://carpedm20.github.io/emoji/docs/#regular-expression

Or use an older version of the module e.g. `pip install emoji==1.6.3`

**Comment by Shin-yue** [comment]
THANKS!

**Comment by Shin-yue** [comment]
> how about that? emoji.get_emoji_regex I didn't find this
