### ISSUE TITLE
Always include release dates in changelog

### ISSUE THREAD

**Issue by impredicative** [carpedm20/emoji#242]
The [changelog](https://github.com/carpedm20/emoji/blob/master/CHANGES.md) currently doesn't show the respective release dates. It is important to be able to see the dates right there.

As good examples, see:

* https://github.com/tkem/cachetools/blob/master/CHANGELOG.rst
* https://github.com/kurtmckee/feedparser/blob/develop/CHANGELOG.rst

The dates can be backfilled too.

**Comment by TahirJalilov** [comment]
done
[changelog](https://github.com/carpedm20/emoji/blob/master/CHANGES.md)
