### ISSUE TITLE
Use https://github.com/iamcal/emoji-data as source for short names

### ISSUE THREAD

**Issue by tgwizard** [carpedm20/emoji#25]
I think we should use https://github.com/iamcal/emoji-data as the source of the emoji data. This will add support for several older code-points (pre the now-standard Unicode format), and it will also make sure that the shortnames (`:smile:`) are the same as what other vendors use.

It will also add support for `:skin-tone-2:` and so on, which are now incorrectly called `:emoji_modifier_fitzpatrick_type-1-2:`.

If you think this is a good idea, I'd be happy to submit a PR trying it out. I'm thinking of adding iamcal/emoji-data as a submodule, and writing a script to generate `core_data.py` from it.

**Comment by coverback** [comment]
@tgwizard I'd love to see this change to use in my project. If you have such a code already, would you mind sharing it, even in a fork? Otherwise I'm gonna have to implement the same change as you were suggesting.

**Comment by coverback** [comment]
Hm, just figured that `use_aliases=True` uses the IDs I wanted, so I'm good.
