### ISSUE TITLE
issues with some emoji

### ISSUE THREAD

**Issue by lsmith77** [carpedm20/emoji#255]
I noticed that some disability related emoji do not seem to be available

```
emoji.emojize(":person_in_motorized_wheelchair:", use_aliases=True)
emoji.emojize(":person_with_probing_cane:", use_aliases=True)

```

**Comment by cvzi** [comment]
I think you are using an old version of the module. 
The current version on [pypi.org](https://pypi.org/project/emoji/) 2.2.0 has them,
update with `python -m pip install --upgrade emoji==2.2.0`

You need to use `language="alias"` parameter now:

```python
emoji.emojize(":person_in_motorized_wheelchair:", language="alias")
emoji.emojize(":person_with_probing_cane:", language="alias")
```
