### ISSUE TITLE
Should the variation selector be considered an emoji?

### ISSUE THREAD

**Issue by marmistrz** [carpedm20/emoji#262]
Consider the following unicode sequence, representing a single emoji. `😀︎`.
```
import emoji
s = b'\\U0001f600\\ufe0f'.decode('unicode_escape')
for c in s:
    print(emoji.is_emoji(c))
```
I would expect this code to print `True` twice. However, the actual behavior is:
```
True
False
```
Is this the expected behavior?

**Comment by cvzi** [comment]
Can you elaborate why you would expect it to be considered an emoji?

Emoji are generally graphical symbols. The emoji selector character on its own is invisible. 
-- 
Enviado desde mi dispositivo Android con K-9 Mail. Por favor, disculpa mi brevedad.

**Comment by marmistrz** [comment]
My intent is to detect strings which represent sequences of emojis only (so that I can use a different font size). This means that I want to return YES for strings like:
```
😀︎
😀︎😀︎😀︎
🤚🏿
```
but NO for 
```
something😀︎
😀︎dfaffd😀︎s😀︎
```
Also, I'd expect a YES answer for the example from the OP, `'\\U0001f600\\ufe0f'`.

The natural approach to do this is 
```
return all(emoji.is_emoji(c) for c in text)
```
which will return `False` for the example from the OP. The fact that this doesn't work if a variation selector is used is far from being obvious and I can expect a lot of code using my buggy approach in the wild.

Since `emoji.is_emoji` only works on the character level, I'll be happy to contribute a helper function that would properly recognize whether a string contains _only_ emojis.

**Comment by marmistrz** [comment]
Given how error prone it is, how about exposing this functionality in `emoji` itself?

**Comment by cvzi** [comment]
I guess we could add it. Do you have a good name for a function in mind?

**Comment by marmistrz** [comment]
Some ideas:
* `is_emoji_sequence`
* `is_only_emoji`
* `represents_only_emoji`
* `pure_emoji` / `pure_emoji_sequence` / `is_pure_emoji_sequence` / `is_purely_emoji`

**Comment by cvzi** [comment]
Sorry, I forgot about it.

Not '_sequence_' because '_sequence_' has a different meaning in the context of Unicode.org.

The others I don't really have a preference. `pure_emoji` is short and , so maybe that one.

**Comment by marmistrz** [comment]
I used `purely_emoji` because `pure_emoji` might mislead the user that there are pure and impure emojis.
