### ISSUE TITLE
square output?

### ISSUE THREAD

**Issue by shenwei356** [carpedm20/emoji#27]
Fail to show in my terminal (utf8), and was `:smile:` not supported :cry: ?

```
>>> import emoji
>>> print(emoji.emojize('Python is :thumbs_up_sign:'))
Python is 👍
>>> print(emoji.emojize('Python is :thumbsup:', use_aliases=True))
Python is 👍
>>> print(emoji.emojize('Python is :smile:'))
Python is :smile:
```

**Comment by carpedm20** [comment]
You should use :

    print(emoji.emojize('Python is :smile:',True))

**Comment by shenwei356** [comment]
@carpedm20 I see, `:smile:` must be an alisase.

For the square, I install a font `gdouros-symbola-fonts` that suppose to enable emoji in terminal, but it still do not work.

**Comment by shenwei356** [comment]
It works after reboot~ Thanks all
