### ISSUE TITLE
Symbols not render

### ISSUE THREAD

**Issue by qingfeng** [carpedm20/emoji#28]
example `:one:` :one:

**Comment by geowurster** [comment]
@qingfeng Looks like `:one:` is GitHub specific.  If you check out [`emoji/unicode_codes.py`](https://github.com/carpedm20/emoji/blob/master/emoji/unicode_codes.py) it's not actually an official emoji, however `:keycap_digit_one:` is.  If you would like `:one:` and other numbers to be available as aliases, please consider reopening this issue and submitting a PR.
