### ISSUE TITLE
Getting UnicodeDecodeError on v2.13.0

### ISSUE THREAD

**Issue by jithinjk** [carpedm20/emoji#305]
With [v2.13.0](https://github.com/carpedm20/emoji/releases/tag/v2.13.0), I'm seeing the below error. 

<img width="915" alt="Screenshot 2024-09-20 at 23 08 56" src="https://github.com/user-attachments/assets/2696a64f-5345-4896-82ef-56720875aae9">
<br><br>

Is it related to JSON file loading? [emoji/unicode_codes/__init__.py](https://github.com/carpedm20/emoji/blob/acfdc1902ac56e053433910dbcc53aff6c03aba7/emoji/unicode_codes/__init__.py)

**Comment by cvzi** [comment]
Could you test if [this patch](https://github.com/cvzi/emoji/commit/0ff7724860bfc0edb11f0c1a0bf03a3fd10831c0) help? If you are using pip you can try like this:

```
pip uninstall emoji
pip install https://github.com/cvzi/emoji/archive/json_unicodeerror.zip
python -c "import emoji"
```

**Comment by jithinjk** [comment]
This works. Thanks
