### ISSUE TITLE
Can't emojize some emojis using keywords

### ISSUE THREAD

**Issue by asurpbs** [carpedm20/emoji#312]
![image](https://github.com/user-attachments/assets/70481f81-7553-42d0-9eeb-11dddc25e3d9)

Tested both Windows and Linux with identical results.

**Comment by arunman1kandan** [comment]
Hey there @asurpbs, 
Arun here the issue is probably because you haven't mentioned the  language='alias' parameter in the emojize method.
Check once if the issue is resolved after setting the same.

Happy Coding ❤️ 

~Arun Manikandan

**Comment by mthlpbs** [comment]
Ok, Thanks

**Comment by asurpbs** [comment]
Ok, Thanks, @arunman1kandan!
