### ISSUE TITLE
Some alias typos

### ISSUE THREAD

**Issue by csaftoiu** [carpedm20/emoji#43]
Some aliases, like :upside-down_face:, should be :upside_down_face: (hyphen turned to underscore). I observed this bug when exporting Slack messages and emojifying them.

The following hack fixed it for now, though it may override some legit aliases:

```
def fix_emoji():
    """Fix emoji's aliases as they have some typos."""
    from emoji import unicode_codes
    for key, val in list(unicode_codes.EMOJI_UNICODE.items()):
        unicode_codes.EMOJI_UNICODE[key.replace('-', '_')] = val
    for key, val in list(unicode_codes.EMOJI_ALIAS_UNICODE.items()):
        unicode_codes.EMOJI_ALIAS_UNICODE[key.replace('-', '_')] = val

    unicode_codes.UNICODE_EMOJI = {v: k for k, v in unicode_codes.EMOJI_UNICODE.items()}
    unicode_codes.UNICODE_EMOJI_ALIAS = {v: k for k, v in unicode_codes.EMOJI_ALIAS_UNICODE.items()}


fix_emoji()
```

**Comment by TahirJalilov** [comment]
it's not a bug. Please check the emoji name here http://www.unicode.org/emoji/charts/full-emoji-list.html#1f643 we replace only space with an underscore
