### ISSUE TITLE
get nothing or exception

### ISSUE THREAD

**Issue by math2001** [carpedm20/emoji#45]
Hi!

I just tried this plugin all I get is nothing or an exception

``` python
Traceback (most recent call last):
  File "C:\add\emoji\test.py", line 4, in <module>
    print(emoji.emojize('Water! :water_wave:'))
  File "C:\Users\math\python\lib\encodings\cp850.py", line 12, in encode
    return codecs.charmap_encode(input,errors,encoding_map)
UnicodeEncodeError: 'charmap' codec can't encode characters in position 7-8: character maps to <undefined>
```

Does anyone have an idea where it could be coming from?

I'm using python **2** on window 8

Mathieu

**Comment by suibaf** [comment]
Same problem!

**Comment by math2001** [comment]
A half solution: http://stackoverflow.com/questions/4374455/how-to-set-sys-stdout-encoding-in-python-3

With this, you don't get any exception (on python 3 at least), but my windows prompt doesn't seem to handle those unicode properly... They work when I build in sublime text though...

**Comment by TahirJalilov** [comment]
may I close this issue?
