### ISSUE TITLE
package name conflict on PyPI

### ISSUE THREAD

**Issue by koliber** [carpedm20/emoji#49]
This package installs into a top-level `emoji`. This conflicts with the top-level of an older project named `django-emoji`. 

It is impossible to use both packages within a single project.

To import from this package, you need to import from `emoji`.

This conflicts with an older project called [`django-emoji`](https://pypi.python.org/pypi/django-emoji). To import from `django-emoji` you also need to import from `emoji`.

`pip` does not have the tooling to rename packages on install. 

PyPI has a policy of unique package names, which this project violates: http://legacy.python.org/dev/peps/pep-0423/ "make sure your project name is unique, i.e. avoid duplicates:"

**Comment by luckydonald** [comment]
If the package is on pypi is called "emoji", I think the module can be called "emoji" as well.

I think "django-emoji" is in error here.

**Comment by signupper** [comment]
@luckydonald your reasoning is sound. 

PEP 423 says to [use the same package name as the project name](http://legacy.python.org/dev/peps/pep-0423/#use-a-single-name). However, it has a big note about the existence of many projects that violate this rule. It seems that there are many projects which have one name for the project and yet install into a package with a different name.

It's a tough case. It is very difficult for an author of a new package to know whether the directory they decide to install into is already used by another project. It's easy to make sure a project name is unique and if everyone followed PEP 423 to the tee, we wouldn't be having this conversation.

Unfortunately, real life is as it is. We have `django-emoji` which is an older project. They decided to install into a package named `emoji`. It seems wrong to ask an existing project to rename the package it installs into when a new project comes around. On the other hand, `django-emoji` is breaking the PEP 423 rule for package naming. 

If we are to solve this, one of the projects will need to rename the package it installs into. Until that happens, it will not be possible to use both of these great projects in a single application.

I will try to bring the author of `django-emoji` into this conversation.

**Comment by luckydonald** [comment]
Is it possible to install as two packages? 
Thinking about backwards compatibility.
Many users will have `import emoji` in theire code.
So usually you can use `emoji`, but if you need `django-emoji` you would use 

Both packages would install as `emoji`, 
but the real `emoji` also as `emoji-emoji`,
and `django-emoji`also as `django-emoji`?

Which will be the `emoji` which get loaded if you install both?
The django one?

**Comment by signupper** [comment]
It is not possible to have both packages installed at once. Each project tries to install into an `emoji` directory inside of `site-packages`. If I recall correctly, the more recently installed one will overwrite the older one.

`pip` does not have a mechanism for overriding the destination package at install time.

Backwards compatibility is going to be an issue, as you've mentioned. 

The options I see are:

- do nothing and keep it impossible to use both packages
- rename the destination package directory of `emoji` to something else like `py_emoji` and force everyone who upgrades the `emoji` package to change their import statements.
- rename the destination package directory of `django-emoji` to something like `django_emoji` and force everyone who upgrades the `django-emoji` package to change their import statements.

There is pain involved in each of these options. If anyone has other options, please chime in.

**Comment by luckydonald** [comment]
Maybe have a `emoji[django-emoji-compat]` version having a different install destination?
I mean it must be possible to rename that folder automatically, before installing.
```python
os.rename("./emoji/", "./emoji-compat")
```

**Comment by signupper** [comment]
It is possible to rename the destination install folder. 

I meant that it is not possible to tell pip, on the command line, to install to an alternate destination. This makes it hard to have both packages installed via a `requirements.pip` file.

**Comment by luckydonald** [comment]
@TahirJalilov How was this resolved?

**Comment by TahirJalilov** [comment]
@luckydonald I think we should not make any changes to the name of the package based on the PEP 423 https://legacy.python.org/dev/peps/pep-0423/#use-a-single-name

**Comment by luckydonald** [comment]
In other words, django-emoji has to change their package name, as this project is named `emoji` and thus the module being named `emoji` as well makes sense. :+1:

**Comment by TahirJalilov** [comment]
yes, absolutely right
