### ISSUE TITLE
Upgrade fails on mac, python 3.4.2

### ISSUE THREAD

**Issue by luckydonald** [carpedm20/emoji#5]
Executed command: ```pip install -U emoji```
Error occurred: ```UnicodeDecodeError: 'ascii' codec can't decode byte 0xf0 in position 738: ordinal not in range(128)```

Update in the PYCharm IDE, maybe a invisible character, like this [issue](https://github.com/ZeevG/python-forecast.io/issues/27#issuecomment-77377042) had? But It could just be PyCharm related instead.

```python
Collecting emoji
  Using cached emoji-0.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/private/var/folders/zh/ntn59b4954l6tldmt4hn8bgc0000gn/T/pycharm-packaging1.tmp/emoji/setup.py", line 17, in <module>
        readme_content = f.read().strip()
      File "/Users/luckydonald/virtualenv3.4.3/bin/../lib/python3.4/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xf0 in position 738: ordinal not in range(128)
    
    ----------------------------------------

    Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/zh/ntn59b4954l6tldmt4hn8bgc0000gn/T/pycharm-packaging1.tmp/emoji
```

**Comment by carpedm20** [comment]
Hmm.. I don't have such problem during installation and I used just a terminal not PyCharm.

	pip install -U emoji
	Downloading/unpacking emoji
	  Downloading emoji-0.2.tar.gz
	  Running setup.py (path:/private/tmp/pip_build_root/emoji/setup.py) egg_info for package emoji

	Installing collected packages: emoji
	  Running setup.py install for emoji

	Successfully installed emoji
	Cleaning up...

**Comment by geowurster** [comment]
I tried to re-create the issue as well without success.  I do know from past experiences that PyCharm sets encoding related environment variables to different values than the terminal.  I declared the encoding in `setup.py` so can you try doing:

`pip install git+https://github.com/geowurster/emoji`

**Comment by luckydonald** [comment]
I can confirm, using the same command as PyCharm, but inside the virtualenv in the terminal, it does install without any problems.

**Comment by geowurster** [comment]
The original command or the one I pasted above?  The command above includes a patch I think might fix the problem.

**Comment by luckydonald** [comment]
The original one. 
Also i looked a bit into it. It is failing at [setup.py:16](https://github.com/carpedm20/emoji/blob/master/setup.py#L16)
```python
with open('README.rst') as f:
    readme_content = f.read().strip()  # failes here
```
The README file (probably UTF-8?) contains non-ascii characters, some emojis.
The are not ascii, so this might be the cause of the error:
```python
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf0 in position 738: ordinal not in range(128)
```
Like described in [this fantastic document](http://nbviewer.ipython.org/github/gmonce/datascience/blob/master/src/1%20-%20Yet%20Another%20Python%20Encoding%20Tutorial.ipynb#Unicode),
this could be caused by a missing encoding parameter like this ```unicode('This string contains €')``` instead of ```unicode('This string contains €', encoding='utf-8')```
Strangely this all look like the problems I had with python 2 binary strings, before switching to py 3.
    
My conclusion is, providing the missing encoding information of the file to read might fix that.
Something like that could do the trick, thus I did not got around to test that.
```python
import codecs
with codecs.open('README.rst', encoding='utf-8') as f:
    readme_content = f.read().strip()
```

**Comment by geowurster** [comment]
Yes, you are correct - it is an encoding issue in the `setup.py`.  I already declared the encoding with `# -*- coding: UTF-8 -*-` and pushed to my fork.  Please test it before I submit a pull request.

`pip install -U git+https://github.com/geowurster/emoji`

**Comment by geowurster** [comment]
@luckydonald any luck?

**Comment by luckydonald** [comment]
Thing is: I can't execute that link in my IDE, and my normal terminal did not even cough the first time.

**Comment by geowurster** [comment]
Hmmm.  @carpedm20 declared the encoding in the `setup.py` and pushed a new release to PyPi so try just `pip install emoji --upgrade`.  If that doesn't work I have a set of debug commands to run so I can understand more about your environment and hopefully figure out what's going on.

**Comment by mxxcon** [comment]
I might have similar problem with PyCharm PE on Windows 8.1.
When it tries to install this package using `pip install -U emoji`, it errors like this:
```
Collecting emoji
  Using cached emoji-0.3.4.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "C:\Users\maxim\AppData\Local\Temp\pycharm-packaging0.tmp\emoji\setup.py", line 18, in <module>
        readme_content = f.read().strip()
      File "C:\Python34\lib\encodings\cp1252.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 602: character maps to <undefined>
    
    ----------------------------------------

Command "python setup.py egg_info" failed with error code 1 in C:\Users\maxim\AppData\Local\Temp\pycharm-packaging0.tmp\emoji
```

**Comment by geowurster** [comment]
@mxxcon ah yeah we set the encoding in the `setup.py` file but that doesn't matter because the characters are coming from an external file.  I switched to using `codecs.open(encoding='UTF-8')` - could you try installing from the [`upgrade-packaging`](https://github.com/carpedm20/emoji/tree/update-packaging) branch?  I think the command is:

```console
pip uninstall emoji && pip install git+https://github.com/carpedm20/emoji.git@update-packaging --upgrade --no-cache
```

Sometimes `pip` gets confused so I tacked an explicit uninstall command on the front and forced it to download with `--no-cache`.  Verify that it installed `v0.3.5` with:

```console
python -c "import emoji; print(emoji.__version__)"
0.3.5
```

**Comment by geowurster** [comment]
[Travis](https://travis-ci.org/carpedm20/emoji/builds/68984818) doesn't like this change but I'm using 3.4 and it worked on my machine.  Give it a shot anyway.  I'll take a closer look later tonight.

**Comment by luckydonald** [comment]
At an different spot, https://travis-ci.org/carpedm20/emoji/jobs/68984820#L249
```python
  if line.strip().startswith('__version__'):
TypeError: startswith first arg must be bytes or a tuple of bytes, not str
```

**Comment by geowurster** [comment]
@mxxcon and @luckydonald can you both try this the command below.  I wonder if this encoding issue is causing the problem in #2.

```
pip uninstall emoji && pip install git+https://github.com/carpedm20/emoji.git@update-packaging --upgrade --no-cache
```

Sometimes pip gets confused so I tacked an explicit uninstall command on the front and forced it to download with --no-cache. Verify that it installed `v0.3.5` with:

```
python -c "import emoji; print(emoji.__version__)"
0.3.5
```

**Comment by mxxcon** [comment]
@geowurster `@update-packaging` seems to worked.
```
Collecting git+https://github.com/carpedm20/emoji.git@update-packaging
  Cloning https://github.com/carpedm20/emoji.git (to update-packaging) to c:\users\maxim\appdata\local\temp\pip-kpmf6pm7-build
Installing collected packages: emoji
  Running setup.py install for emoji
Successfully installed emoji-0.3.4
```

**Comment by geowurster** [comment]
@luckydonald FYI looks like you were right about specifying the encoding when opening the file.
