### ISSUE TITLE
:one: alias doesn't work

### ISSUE THREAD

**Issue by Jackamma** [carpedm20/emoji#51]
emojize(":one:") doesn't print the emoji. I found that the correct alias is ":keycap_digit_one:". Btw the emoji that appears is different from the Apple one. I found that the Apple emoji is composed by two character, the first one is the number and the second one is chr(8419), so for me the best solution was to substitute emojize(":one:") with "1"+chr(8419). This works also for other numbers (the second character is always the same).

**Comment by EnforcerZhukov** [comment]
Hi, I'm working on a Telegram Bot and I want to include numbers from 0 to 10. 10 is the only number working. It has something to do with the alias. I managed to print 0~9 emojis using keycap_digit_zero, keycap_digit_one, and so on, as the name, and use_aliases=False. But on Telegram, they spawn ugly, they spawn like text and really buggy.
