### ISSUE TITLE
Getting black and white Emojis

### ISSUE THREAD

**Issue by jcesarprog** [carpedm20/emoji#63]
Here is my code.
`import emoji'

'print(emoji.emojize("Hello :earth_americas:", use_aliases=True))`

Here is the output.

![emoji black-white](https://user-images.githubusercontent.com/30150182/28550317-5eef65e6-70b6-11e7-9c57-edeed0ef7b91.png)

tried others but still got no colors on both windows or linux..still no colors..

**Comment by ASMfreaK** [comment]
It has to do with your font setup in pycharm. Colorful emoji are not very good supported with software at the moment.

**Comment by artbava** [comment]
Same issue here. There is nothing to do with Pycharm font setup, as my friend uses the same setup with no issues.

**Comment by sevelee** [comment]
On Mac OS X emoji characters are rendered as colored images. On Windows and Linux emoji are rendered as monochrome characters. [https://blog.jetbrains.com/idea/2016/12/intellij-idea-2017-1-eap-is-open/](url)

**Comment by emanchado** [comment]
You may have to install additional fonts that have colour emojis, eg. https://www.google.com/get/noto/help/emoji/

**Comment by truthdoug** [comment]
Emojis are rendered by the OS/tool used. This python package merely translates to and from unicode. If your OS or tool isn't rendering it in color, it's not something that can be fixed by this package.

This issue can be closed.
