### ISSUE TITLE
Release update to PyPI

### ISSUE THREAD

**Issue by svleeuwen** [carpedm20/emoji#72]
Especially this commit https://github.com/carpedm20/emoji/commit/b93de0dfb165c1de4051f6cd6b9ead174ab6c0e2 that's from June 2017 would be really helpful to have on the package index.

**Comment by truthdoug** [comment]
There have been two updates to pypi since this issue was opened. See the [release history](https://pypi.org/project/emoji/#history)

**Comment by truthdoug** [comment]
This issue can be closed.
