### ISSUE TITLE
Unable to detect flag emojis

### ISSUE THREAD

**Issue by Nomiluks** [carpedm20/emoji#77]
``import emoji

def emoji_lis(string):
    _entities = []
    for pos,c in enumerate(string):
        if c in emoji.UNICODE_EMOJI:
            print("Matched!!", c ,c.encode('ascii',"backslashreplace"))
            _entities.append({
                "location":pos,
                "emoji": c
                })
        else:
            print(c ,c.encode('ascii',"backslashreplace"))
    return _entities

#emoji_lis("مدیحہ🇵🇰")
emoji_lis("🇵🇰 👧🏿")

Output: 
[{u'emoji': u'\U0001f467', u'location': 3},
 {u'emoji': u'\U0001f3ff', u'location': 4}]

**Comment by kittenswolf** [comment]
Flags consist of two emojis.

**Comment by kairstenfay** [comment]
I am also having this issue. The emoji for the US flag, :us:, is being split into  🇺 🇸.
