### ISSUE TITLE
Add a method to get the names of all emojis in an indexed/serialized format

### ISSUE THREAD

**Issue by niladridutt** [carpedm20/emoji#81]
I want to get the names of all emojis in an indexed way. This would be really helpful to build a Deep learning model to convert text to emoji. I had to do a work around to get this working.

**Comment by JimCurryWang** [comment]
@niladridutt 

There is an dictionary called ``EMOJI_UNICODE`` .
Maybe that is  what you want ?
```python
import emoji

emoji.EMOJI_UNICODE.get(':Belarus:')
```
```python
>>>  🇧🇾
```

**Comment by niladridutt** [comment]
@JimCurryWang Not really. I wanted to get a list of all emojis through which I could iterate and build a map. Anyway, I've written my own function now.
