### ISSUE TITLE
Error in documentation

### ISSUE THREAD

**Issue by dinel** [carpedm20/emoji#82]
The documentation for demojize is not correct. The output of 

`>>> print(emoji.demojize(u"Unicode is tricky 😯", delimiters=(" __", "__ ")))`

is 

`Unicode is tricky  __hushed_face__ `

https://github.com/carpedm20/emoji/blob/2b7fa78bd59ee9c5aa55b21d3f3872d345dc09be/emoji/core.py#L67

**Comment by hedythedev** [comment]
Yes, I noticed that too but unfortunately it seems that this project is no longer maintained (#126)
