### ISSUE TITLE
module 'emoji' has no attribute 'emojize'

### ISSUE THREAD

**Issue by krishnac7** [carpedm20/emoji#83]
The above error is popping up 
![screen shot 2018-07-01 at 10 16 44 pm](https://user-images.githubusercontent.com/7543641/42136613-793e7fe4-7d7c-11e8-96f6-fda6c9e02bf0.png)

**Comment by cogk42** [comment]
Maybe you have an `emoji.py` script in your working directory that is imported instead of the `emoji` module ?

**Comment by hrvoojex** [comment]
This is exactly what happend to me. My script was emoji.py. Renamed it and it's working now.

**Comment by rose-wasilewska** [comment]
That is nice hrvoojex... I had the same problem. I changed the name and it worked. Yeah... But then I did another file (named tbk.py - no meaning really) and it is not working again. I change the name literally to 'change'..it is not working!!!!!!!!! So there is another bug. Not only the name or IDK
