### ISSUE TITLE
Not working correctly under Windows 10 with Python 3

### ISSUE THREAD

**Issue by walchko** [carpedm20/emoji#84]
Under Windows 10, using python 3.7, the only emoji I have successfully gotten to work is the thumbs up one.

```bash
Kevin.Walchko@DFEC-4508ZK ~ $ python3
Python 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD6
4)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from emoji import emojize
>>> print(emojize(":smile:"))
:smile:
>>> print(emojize(":thumbs_up:"))
👍
```

**Comment by ohad24** [comment]
+1

**Comment by CosasDePuma** [comment]
If I try to run the Python 3.7 interpreter from a Powershell Terminal and I got this result:

```python
>>> print(emoji.emojize('Python is :thumbs_up:'))
Python is □□
```

Not exactly this squares, but similar.

**Comment by TahirJalilov** [comment]
You have to use aliases
>>> from emoji import emojize
>>> print(emojize(":smile:", use_aliases=True))
😄
>>> print(emojize(":thumbs_up:"))
👍
