### ISSUE TITLE
trademark symbols are emojis?

### ISSUE THREAD

**Issue by kwhumphreys** [carpedm20/emoji#90]
what is the reasoning to include ® and ™ as emojis?

**Comment by TahirJalilov** [comment]
Don't understand your question

**Comment by kwhumphreys** [comment]
Why is U+2122 included in `get_emoji_regexp` here https://github.com/carpedm20/emoji/blob/master/emoji/unicode_codes/en.py#L2989 when it's a letterlike symbol, not an emoji https://en.wikipedia.org/wiki/Letterlike_Symbols ?

Also U+00A9 https://github.com/carpedm20/emoji/blob/master/emoji/unicode_codes/en.py#L712

**Comment by TahirJalilov** [comment]
Because the are exist in the list of all emojis. Please check here:
https://www.unicode.org/emoji/charts/full-emoji-list.html#00a9
https://www.unicode.org/emoji/charts/full-emoji-list.html#2122

**Comment by TahirJalilov** [comment]
@kwhumphreys May I close this issue?
