### ISSUE TITLE
Language option for emoji descriptions

### ISSUE THREAD

**Issue by mertkosan** [carpedm20/emoji#98]
While demojizing or emojizing, there can be a language option which would be awesome...
- The function may take one more parameter which will be 'lang' (such as 'en', 'es', 'tr'...), then according to that parameter, transform the emoji... 
- The community can help for the translation as well, I can do Turkish one.

**Comment by verhovsky** [comment]
The Unicode Consortium already provides translations http://unicode.org/cldr/charts/dev/annotations/index.html

**Comment by manueltonneau** [comment]
It now exists for Spanish and Portuguese (see README). To use it, you need to clone the package, cd into it and install the package with `pip install .`.
